app/urls.py
from django.contrib import admin
from django.contrib.sessions.backends import file
from django.urls import path,include

from .views import *

app_name = 'app'

urlpatterns = [
    path('all/',index,name='all'),
    path('python/',index2,name='index2'),
    path('html/', index_html, name='index_html'),
    path('html/python/', index2, name='index_htm'),
    path('rubric/<int:pk>/', detail, name='detail'),
    path('bb/<int:pk>/', detail_bb, name='detail_bb'),
    path('add-bb/',cache_page(300)(add_bb), name='add_bb'),
    path('stream/',stream,name='stream'),
    path('file/',file_response,name='file'),
    path('json/',json_response,name='json'),
    path('update/<int:pk>/bb/',update_bb,name='update_bb'),
    path('delete/<int:pk>/bb/',delete_bb,name='delete_bb'),
    #Class Views
    path('create/class/',BbCreateView.as_view(),name='create'),
    path('by_rubric/class/<int:rubric_id>/',BbByRubricTemplateView.as_view(),name='by_rubric'),
    path('rubric_detail/class/<int:rubric_id>/',RubricDetailView.as_view(),name='rubric_detail'),
    path('bb_detail/class/<int:pk>/',BbDetailView.as_view(),name='bb_detail'),
    path('all/class/',BbListView.as_view(),name='all_class'),
    path('update/bb/class/<int:pk>/',BbUpdateView.as_view(),name='update_bb_class'),
    path('delete/bb/class/<int:pk>/',BbDeleteView.as_view(),name='delete_bb_class'),

    #date
    path('archive/',BbIndexArchiveView.as_view(),name='archive'),
    path('archive/<int:year>/',BbYearArchiveView.as_view(),name='archive-year'),
    path('archive/<int:year>/<int:month>/', BbMonthArchiveView.as_view(),name='archive-month'),
    path('archive/<int:year>/week/<int:week>/', BbWeekArchiveView.as_view(),name='archive-week'),
    path('archive/<int:year>/<int:month>/<int:day>/', BbDayArchiveView.as_view(),name='archive-day'),
    path('archive/today/',BbTodayArchiveView.as_view(),name='archive-today'),
    path('redirect/',BbRedirectView.as_view(),name='redirect'),
    path('merge/<int:rubric_id>/',MergeBbRubricView.as_view(),name='merge'),
    path('contact/',ContactFormView.as_view(),name='contact'),
    path('all-bboards/',TemplateAllBboard.as_view(),name='all_bboards'),
    path('test/',TestView.as_view(),name='test'),
    path('bootstrap/',BootstrapFormView.as_view(),name='bootstrap'),
    path('paginator/',bb_paginator,name='paginator'),
    path('paginator-class/',BbListViewPaginator.as_view(),name='paginator-class'),
    path('rubric-formset/',RubricSetView.as_view(),name='rubric_formset'),
    path('quiz/<int:pk>/',QuizFormsetView.as_view(),name='quiz_formset'),
    path('atomic/',manual_transaction_example,name='atomic'),
    path('atomic-auto/', atomic_transaction_example, name='atomic-auto'),
    path('json-response/', BbJsonView.as_view(), name='json-response'),
    path('cache/',cache_backend,name='cache'),
    path('filter/',filter,name='filter'),

    path("doclist/", docs_list, name="docs_list"),
    path("photos/", photos_list, name="photos_list"),

    path("upload/doc/", UploadDocumentView.as_view(), name="upload_doc"),
    path("upload/doc/many/", UploadManyDocsView.as_view(), name="upload_many"),
    path("upload/photo/", UploadPhotoView.as_view(), name="upload_photo"),

    path("delete/doc/<int:pk>/", delete_document, name="delete_document"),
    path("delete/photo/<int:pk>/", delete_photo, name="delete_photo"),

    path("gallery/", gallery_list, name="gallery_list"),

    path("upload/resized/", UploadResizedPhotoView.as_view(), name="upload_resized"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls',namespace='app')),
    path('films/',include('films.urls',namespace='films')),
    path('core/',include('core.urls')),
    path('webcore/',include('webcore.urls')),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('accounts/logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('accounts/password_change/',auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),
    #email
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset_form.html',
             email_template_name='registration/password_reset_email.txt',
             subject_template_name='registration/password_reset_subject.txt',
         ),
         name='password_reset'),

    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from precise_bbcode.fields import BBCodeTextField

User=get_user_model()

class Post(models.Model):
    title=models.CharField(max_length=100)
    body=models.TextField()
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    content=BBCodeTextField(default="")

    class Meta:
        permissions=[
            ("view_secret_post","Can view secret post")
        ]
    def __str__(self):
        return self.title

templates/add_bb.html
{% extends "base.html" %}

{% block title %}
Создание поста
{% endblock %}

{% block content %}

<div class="form-wrapper">
  <div class="form-card">
    <h1>Добавить Публикацию</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Отправить" />
    </form>
  </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load cache %}
  {% load bbcode_tags %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'form_style.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
  <meta charset="UTF-8">
    <title>{% block title %}   {%endblock %}</title>
</head>
<body>
<h1>{{quote}}</h1>
<h2>{{current_time}}</h2>


<header>

  <nav>
    <ul>
      {% for item in menu %}
      <li class="{% if request.resolver_match.url_name == item.url_name %}active{% endif %}">
        <a href="{% url item.url_name %}">{{item.title}}</a>
      </li>

      {% endfor %}
    </ul>
  </nav>
</header>

  <nav class="navbar">
    <div class="navbar-container">
      <a href="#" class="logo">Мой Сайт</a>
      <ul class="nav-links">
        <li><a href="{% url 'app:all_class' %}">Главная</a></li>
        <li><a href="{% url 'app:create' %}">Создать пост</a></li>
        <li><a href="{% url 'app:archive' %}">Архив</a></li>
        <li><a href="{% url 'app:contact' %}">Контакты</a></li>
      </ul>
    </div>
  </nav>
{% if messages %}
<ul>
  {% for message in messages %}
  <li class="{{ message.tags }}">{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}





{% block content %}



{% endblock %}

  <footer class="footer">
    <div class="footer-container">
      <p>&copy; 2025 МойСайт. Все права защищены.</p>
      <div class="socials">
        <a href="#">VK</a>
        <a href="#">Telegram</a>
        <a href="#">Instagram</a>
      </div>
    </div>
  </footer>
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}    {%endblock%}</title>
</head>
<body>
  <nav>
  {% if user.is_authenticated %}
    <p>Добро пожаловать, {{ user.username }}!</p>
    <a href="{% url 'home' %}">Главная</a>
    <a href="{% url 'logout' %}">Выйти</a>
    {% if perms.core.view_secret_post %}
    <a href="{% url 'post_list' %}">List Post</a>
    {% endif %}
  {% else %}
    <a href="{% url 'login' %}">Войти</a>
  {% endif %}
  </nav>
  <hr>


{% block content %}

{% endblock %}

</body>
</html>

templates/bb_paginator.html
{% extends 'base.html' %}

{% block title %}
Paginator Example
{% endblock %}

{% block content %}

<h1 class="main-title">Посты:</h1>

{% for bb in page_obj %}
  <div class="post-detail-card">
    <h2 class="post-title">{{ bb.title }}</h2>
    <p class="post-content">{{ bb.content }}</p>
    <p class="post-price">Цена: {{ bb.price }} $</p>
    <p class="post-date">Дата публикации: {{ bb.published }}</p>
  </div>
{% empty %}
  <p class="no-data">Нет постов для отображения.</p>
{% endfor %}

{% if page_obj.has_other_pages %}
  <nav class="pagination">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}&per_page={{ page_obj.paginator.per_page}}">&laquo;</a>
    {% else %}
      <span>&laquo;</span>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if num == page_obj.number %}
        <span>{{ num }}</span>
      {% elif num >= page_obj.number|add:'-2' and num <= page_obj.number|add:'2' %}
        <a href="?page={{ num }}&per_page={{ page_obj.paginator.per_page }}">{{num}}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}&per_page={{ page_obj.paginator.per_page}}">&raquo;</a>
    {% else %}
      <span>&raquo;</span>
    {% endif %}
  </nav>

  <p class="pagination-info">
    Показаны {{ page_obj.start_index }}–{{ page_obj.end_index }} из {{ page_obj.paginator.count }} постов.
  </p>
{% endif %}

{% endblock %}

templates/bb_paginator_custom.html
{% extends "base.html" %}
{% block title %}Paginator Example{% endblock %}

{% block content %}

<h1 class="main-title">Посты:</h1>

{% for bb in page_obj %}
  <div class="post-detail-card">
    <h2 class="post-title">{{ bb.title }}</h2>
    <p class="post-content">{{ bb.content }}</p>
    <p class="post-price">Цена: {{ bb.price }} $</p>
    <p class="post-date">Дата публикации: {{ bb.published }}</p>
  </div>
{% empty %}
  <p class="no-data">Нет постов для отображения.</p>
{% endfor %}

{% if page_obj.has_other_pages %}
  <nav class="pagination">

    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}&per_page={{ page_obj.paginator.per_page }}">&laquo;</a>
    {% else %}
      <span class="disabled">&laquo;</span>
    {% endif %}

    {% for real, label in neg_page_range %}
      {% if real == page_obj.number %}
        <span class="current">
          {{ label }}
        </span>
      {% else %}
        <a href="?page={{ real }}&per_page={{ page_obj.paginator.per_page }}">
          {{ label }}
        </a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}&per_page={{ page_obj.paginator.per_page }}">&raquo;</a>
    {% else %}
      <span class="disabled">&raquo;</span>
    {% endif %}

  </nav>

  <p class="pagination-info">
    Показаны {{ page_obj.start_index }}–{{ page_obj.end_index }}
    из {{ page_obj.paginator.count }} записей.
  </p>
{% endif %}
{% endblock %}

templates/bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load bootstrap5 %}
    {% bootstrap_css %}

<form method="post">
    {% csrf_token %}
     {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
</body>
</html>

templates/bullet.html
<ul>
  {% for i in items %}

    <li>{{i}}</li>
  {% endfor %}
</ul>
<p><em>Всего элементов: {{count}}</em></p>

templates/contact.html
{% extends "base.html" %}

{% block title %}
Контакты
{% endblock %}

{% block content %}

<div class="form-wrapper">
  <div class="form-card">
    <h1>Отправить сообщение</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Отправить" />
    </form>
  </div>
</div>

{% endblock %}

templates/date.html
{% extends "base.html" %}

{% block title %}
Архив
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="main-title">Архив дат</h1>

  {% if latest %}
    <div class="ads-grid">
      {% for b in latest %}
        <div class="ad-card">
          <h2 class="ad-title">
            <a href="{{ b.get_absolute_url }}">{{ b.title }}</a>
          </h2>
          <p class="ad-price">{{ b.price }} ₽</p>
          <p class="ad-desc">{{ b.title_and_price }}</p>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p class="no-data">Объявлений пока нет.</p>
  {% endif %}
</div>
{% endblock %}

templates/delete_bb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Delete Page</h1>
<h1>Do you want to delete this data?</h1>
<h2>{{ bb.rubric.name }}</h2>
<p> {{bb.title}} - {{bb.price}}</p>
<p> {{bb.content}} - {{bb.published}}</p>
<form action="{% url 'app:delete_bb_class' bb.pk %}" method="post">
    {% csrf_token %}
    <button type="submit"> Удалить </button>
</form>
</body>
</html>

templates/detail_bb.html
{% extends "base.html" %}

{% block title %}
{{ bb.title }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="post-detail-card">
    <h1 class="post-title">{{ bb.title }}</h1>
    <h3 class="post-rubric">Рубрика: {{ bb.rubric.name }}</h3>
    <p class="post-price">Цена: <span>{{ bb.price }} ₽</span></p>
    <p class="post-content">{{ bb.content }}</p>
    <p class="post-date">Опубликовано: {{ bb.published|date:"d.m.Y H:i" }}</p>

    <div class="post-actions">
      <a class="btn btn-update" href="{% url 'app:update_bb' bb.pk %}">Редактировать</a>

      <form action="{% url 'app:delete_bb' bb.pk %}" method="post" class="delete-form">
        {% csrf_token %}
        <button type="submit" class="btn btn-delete">Удалить</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/hw.html
{% extends "base.html" %}

{% block content %}
  <h1>Объявления</h1>

  <ul>
    {% for bb in bbs %}
      <li>
        <a href="{% url 'app:detail_bb' bb.pk %}">{{ bb.title|title }}</a>
        - Цена: {{ bb.price }}$
        {% if bb.content %}
          <p>{{ bb.content|truncatechars:50 }}</p>
        {% endif %}
      </li>
    {% empty %}
      <li>Объявлений пока нет.</li>
    {% endfor %}
  </ul>

  <h2>Рубрики</h2>
  <ul>
    {% for rubric in rubrics %}
      <li><a href="{% url 'app:detail' rubric.pk %}">{{ rubric.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
Объявления
{% endblock %}

{% block content %}

<div class="rubrics">
  {% for rub in rubrics %}
    <a class="rubric-link" href="{{ rub.get_absolute_url }}">{{ rub.name }}</a>
  {% endfor %}
</div>




<div class="container">
  <h1 class="main-title">Список объявлений</h1>

  {% if bbs %}
    <div class="ads-grid">
      {% for b in bbs %}
        <div class="ad-card">
          <h2 class="ad-title">
            <a href="{{ b.get_absolute_url }}">{{ b.title }}</a>
          </h2>
          <p class="ad-price">{{ b.price }} ₽</p>
          <p class="ad-desc">{{ b.title_and_price }}</p>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p class="no-data">Объявлений пока нет.</p>
  {% endif %}
</div>
{% endblock %}

templates/rubric_formset.html
{% extends "base.html" %}

{% block title %}
Создание Рубрик
{% endblock %}

{% block content %}

<div class="form-wrapper">
  <div class="form-card">
    <h1>Рубрики</h1>
    <form method="post">
      {% csrf_token %}
      {{ formset.as_p }}
      <input type="submit" value="Отправить" />
    </form>
  </div>
</div>

{% endblock %}